name: Build SunamoCompare

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCompare
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCompare/SunamoCompare.csproj

    - name: Build
      run: dotnet build SunamoCompare/SunamoCompare.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCompare.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCompare.Tests/SunamoCompare.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCompare.Tests/SunamoCompare.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCompare.Tests/SunamoCompare.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
